[languages]
rust = ["rustfmt"]
go = ["gofmt"]
python = ["black --fast -"]
r = ["R --slave --no-restore --no-save -e options(styler.colored_print.vertical=FALSE);con<-file('stdin');styler::style_text(readLines(con));close(con)"]
